### ISSUE TITLE
Cannot install. Ubuntu 16.04 LTS Xenial

### ISSUE THREAD

**Issue by ghost** [ubports/unity8-desktop-install-tools#17]
Hello,
trying to install unity8 using the install script 

> bash <(wget -qO- https://raw.githubusercontent.com/ubports/unity8-desktop-install-tools/master/install.sh)

All good until the `press enter to continue` part. After pressing enter I get this error:

```
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 unity8-desktop-session : Depends: qtmir-desktop but it is not going to be installed
                          Depends: qtubuntu-appmenutheme but it is not going to be installed
                          Depends: qtubuntu-desktop but it is not going to be installed
                          Depends: unity8 but it is not going to be installed
                          Recommends: qtubuntu-print but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

I've searched the forums and tried a couple solutions but none of them work. 
What other info do you think would be relevant to add ?

**Comment by ghost** [comment]
Is it possible to maybe add a remove script? For when a simple sudo apt remove won't do.
Atm I am stuck with chrome not starting at all (typing this from Firefox) and 15-20 seconds delay to open the terminal with ctrl-alt-t. It starts immediately when clicking it from applications tab.

**Comment by dekkerj1** [comment]
Same error after dist-upgrade. 
jaap@antares-ubuntu:~$  uname -a
Linux antares-ubuntu 4.13.0-36-generic #40~16.04.1-Ubuntu SMP Fri Feb 16 23:25:58 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by ismaelbonato** [comment]
Same error here.

------------------------------------------------------------------------------------
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package qtbase-abi-5-9-0 is a virtual package provided by:
  libqt5core5a 5.9.1+dfsg+ubports [Not candidate version]

E: Package 'qtbase-abi-5-9-0' has no installation candidate
------------------------------------------------------------------------------------

Linux unity8 4.13.0-36-generic #40~16.04.3-Ubuntu.

I cannot Test Unity8 builds without that. because  Settings schema 'com.canonical.Unity8' is not installed.

ps: It works great with 18.04 Gnome (Missing icons) and KDE.

**Comment by JesusValeraDev** [comment]
Me too.

```
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 unity8-desktop-session : Depends: qtmir-desktop but it is not going to be installed
                          Depends: qtubuntu-appmenutheme but it is not going to be installed
                          Depends: qtubuntu-desktop but it is not going to be installed
                          Depends: unity8 but it is not going to be installed
                          Recommends: qtubuntu-print but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by Pajn** [comment]
From my Telegram posts:

qtmir-desktop can not be installed due to qtbase-abi-5-9-0 having no installation candidate

qtbase-abi-5-9-0 is actually provided by an older version of libqt5core5a but installing that version manually does not help as other packages needs the newer version. Seems like some packages have been upgraded but others not.

It seems to be xenial_-_mir26 that is not up to speed with xenial

EDIT: It seems to be inconsistencies even between packages in xenial

**Comment by mauron85** [comment]
Is there any plan to make this work on Xenial?

**Comment by littlephone** [comment]
@mauron85  @Pajn  Same issue in bionic but for different version on qtbase-abi.  We are stuck at qtbase-abi-5-9-2 for bionic as well. @AlanGriffiths said it's because of the update of qt and needs a "rebuild of world", but I didn't see any changes to the issue. No clues for now.

**Comment by Teslaturgy** [comment]
Is there any workaround for this yet?

**Comment by jonnius** [comment]
Looks like something has changed already, but still dependency issues: 
```
The following packages have unmet dependencies:
 unity8-desktop-session : Depends: unity8 but it is not going to be installed
                          Recommends: qtubuntu-print but it is not going to be installed
```
For example **unity8-schemas** wants to remove **unity-schemas**, which other unity8-packages still depend on.

It is 3 months already that unity8 can't be installed on Ubuntu 16.04. Is it different on Ubuntu 18.04?

**Comment by Pajn** [comment]
> Is it different on Ubuntu 18.04?

On 18.04 is it even worse as unity8 would need to be ported to a modern Mir that utilizes Wayland.
16.04 just requires a "rebuild world".

**Comment by Flohack74** [comment]
Guys, please understand that unity8 is not our main focus currently, as we are still the team that focuses on the phone-related issues of Ubuntu Touch. We took over a bit the development of unity8 also, since the Yunit project seems to have failed on kickstarting their efforts. But we are not able to work full power on unity8 for desktop. So, when you see little progress, its just normal :)

**Comment by jonnius** [comment]
Sorry for the impatience in my comment. Thanks for doing this great work!

**Comment by pwanchope** [comment]
I just hit this with my raspberry pi.  Managed to install unity 8 (on top of a lubuntu-desktop) by downgrading a number of packages and removing the update/security/backports repos from my sources.list.  unity8-desktop-session still complains.  For this I think the ppa ci-train-ppa-service/stable-phone-overlay needs to be added.  That's what https://github.com/ubports/rootstock-ng/blob/master/rootstock-touch appears to be doing anyway.  Bedtime now....will try that tomorrow....zzzz

**Comment by jonnius** [comment]
I just tried and was able to install Unity8 without any dependency issue on Ubuntu Mate 16.04 for Raspberry Pi. So this seems to be fixed.
